// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDSNZma0jGe6UrJjMtA3zNn5a2UgQYhGE',
    appId: '1:893910750279:web:f2e075e6cf30ce052a4d62',
    messagingSenderId: '893910750279',
    projectId: 'todolist-bbc0e',
    authDomain: 'todolist-bbc0e.firebaseapp.com',
    storageBucket: 'todolist-bbc0e.appspot.com',
    measurementId: 'G-T24V7K3Q4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMgj4eEQmNsavdYRmX7NLpkZbpc-pxS1Q',
    appId: '1:893910750279:android:59fa3bc910a441492a4d62',
    messagingSenderId: '893910750279',
    projectId: 'todolist-bbc0e',
    storageBucket: 'todolist-bbc0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsKzvg1StK5blTDzJTKXE9aA7obaIH6Kg',
    appId: '1:893910750279:ios:16c27f0b743f338d2a4d62',
    messagingSenderId: '893910750279',
    projectId: 'todolist-bbc0e',
    storageBucket: 'todolist-bbc0e.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsKzvg1StK5blTDzJTKXE9aA7obaIH6Kg',
    appId: '1:893910750279:ios:f84e9d436ba7effc2a4d62',
    messagingSenderId: '893910750279',
    projectId: 'todolist-bbc0e',
    storageBucket: 'todolist-bbc0e.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
